# Generated by Django 3.2.19 on 2023-09-19 07:28

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImageBackendExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACL_TYPE', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='pvt', max_length=11)),
                ('image', models.URLField(default='https://www.edx.org/contentful/ii9ehdcj88bc/2SkUwC7Kf9G5I5b49hjVgu/1fa2453e92e46d980f9f99cf08a51e73/image_processing.jpg', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultStorageExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='public_images_1/images')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateImageExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='test', default_acl='private', querystring_auth=True, querystring_expire=500), upload_to='private_storages/images')),
            ],
        ),
        migrations.CreateModel(
            name='PublicImageExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='public_images_2/images')),
            ],
        ),
    ]
