# Generated by Django 3.2.19 on 2023-09-17 17:16

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImageBackendExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='custom_backend/images')),
            ],
        ),
        migrations.CreateModel(
            name='ImageByDefaultStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='public_images_1/images')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='awaisq', default_acl='private', querystring_auth=True, querystring_expire=500), upload_to='private/images')),
            ],
        ),
        migrations.CreateModel(
            name='PublicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='public_images_2/images')),
            ],
        ),
    ]
