# Generated by Django 3.2.19 on 2023-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebydefaultstorage',
            name='image',
            field=models.FileField(upload_to='default_storages/images'),
        ),
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.FileField(upload_to='private/images'),
        ),
    ]
