# Generated by Django 3.2.19 on 2023-09-17 14:56

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20230917_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImageBackendExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='custom_backend/images')),
            ],
        ),
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='awaisq', default_acl='private', querystring_auth=True, querystring_expire=500), upload_to='private/images'),
        ),
        migrations.AlterField(
            model_name='publicimage',
            name='image',
            field=models.FileField(upload_to='public/images'),
        ),
    ]
